//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enact.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allocation
    {
        public long Allocation_ID { get; set; }
        public int Block { get; set; }
        public bool isAllocated { get; set; }
        public string Combination_ID { get; set; }
        public long Audit_ID { get; set; }
    }
}
