//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enact.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combination
    {
        public string Combination_ID { get; set; }
        public bool Modification_A { get; set; }
        public bool Modification_B { get; set; }
        public bool Modification_C { get; set; }
        public bool Modification_D { get; set; }
        public bool Modification_E { get; set; }
        public bool Modification_F { get; set; }
    }
}
