//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enact.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAddress
    {
        public long ID { get; set; }
        public string Email_address { get; set; }
        public Nullable<bool> Completed_survey { get; set; }
        public Nullable<bool> Sent_voucher { get; set; }
        public Nullable<int> Trial_ID { get; set; }
    }
}
