//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enact.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModificationA_Content
    {
        public long ID { get; set; }
        public string Title_One { get; set; }
        public string Title_Two { get; set; }
        public string Description_One { get; set; }
        public string Description_Two { get; set; }
        public string ImagePath { get; set; }
        public bool ModState { get; set; }
        public long Audit_ID { get; set; }
    }
}
