//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enact.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public long ID { get; set; }
        public string Response_1 { get; set; }
        public string Response_2 { get; set; }
        public string Response_3 { get; set; }
        public string Response_4 { get; set; }
        public string Response_5 { get; set; }
        public long Trial_ID { get; set; }
    }
}
